package org.usfirst.frc5442.Fred.commands;

//RobotBuilder Version: 1.5
//
//This file was generated by RobotBuilder. It contains sections of
//code that are automatically generated and assigned by robotbuilder.
//These sections will be updated in the future when you export to
//Java from RobotBuilder. Do not put any code or make any change in
//the blocks indicating autogenerated code or it will be lost on an
//update. Deleting the comments indicating the section will prevent
//it from being updated in the future.



import java.util.function.ToDoubleBiFunction;

import javax.jws.Oneway;

import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc5442.Fred.OI;
import org.usfirst.frc5442.Fred.Robot;

/**
* Command to drive straight based off of trim value on joystick
*
*/
public class  DriveStraight extends Command {

 public DriveStraight() {
     // Use requires() here to declare subsystem dependencies
     // eg. requires(chassis);

     requires(Robot.driveTrain);
 	}

 	// Called just before this Command runs the first time
 	protected void initialize() {
 	}

 	// Called repeatedly when this Command is scheduled to run
 	protected void execute() {
 		 Robot.driveTrain.driveStraight(OI.joystick1.getRawAxis(3));
 	 
 	}

 	// Make this return true when this Command no longer needs to run execute()
 	protected boolean isFinished() {
 		return false;
 	}

 	// Called once after isFinished returns true
 	protected void end() {
 	}

 	// Called when another command which requires one or more of the same
 	// subsystems is scheduled to run
 	protected void interrupted() {
 	}
}
