// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5442.Fred.commands;

import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc5442.Fred.OI;
import org.usfirst.frc5442.Fred.Robot;

/*
 * *Command to move the drive train subsystem based on controller values. Command will run for the time
 * need to execute or until another command which requires one or more of the 
 * same subsystems is scheduled to run.
 */
public class  DriveWithController extends Command {

    public DriveWithController() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        requires(Robot.driveTrain);
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	//Robot.driveTrain.tankDrive(OI.xboxController.getRawAxis(5), OI.xboxController.getRawAxis(1));
    	Robot.driveTrain.tankDrive(OI.joystick2.getY(), OI.joystick1.getY());
    	//System.out.println(Robot.encoders.encoderRight.getDistance());
    	
    	//*if(OI.joystickRight.getY()>0.1 || OI.joystickRight.getY()<-0.1)
    	//{
    		//Robot.driveTrain.tankDrive(OI.joystickRight.getY(), OI.joystickRight.getY());
    	//} else if(OI.joystickRight.getZ()>0.1 || OI.joystickRight.getZ()<-0.1)
    	//{
    		//Robot.driveTrain.tankDrive(OI.joystickRight.getZ(), -1 * OI.joystickRight.getZ());
    	//}
    	
    	
    	//Robot.driveTrain.tankDrive(OI.xboxController.getRawAxis(5), OI.xboxController.getRawAxis(1));
    	//Robot.driveTrain.tankDrive(OI.joystickRight.getY(), OI.joystickRight.getTwist());
    	
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
