// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5442.Fred.subsystems;

import org.usfirst.frc5442.Fred.*;
import org.usfirst.frc5442.Fred.commands.DriveWithController;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class DriveTrain extends Subsystem {
    SpeedController talonController1 = RobotMap.driveTrainTalonController1;
    SpeedController talonController2 = RobotMap.driveTrainTalonController2;
    SpeedController talonController3 = RobotMap.driveTrainTalonController3;
    SpeedController talonController4 = RobotMap.driveTrainTalonController4;
    RobotDrive robotDrive = RobotMap.driveTrainRobotDrive;

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        setDefaultCommand(new DriveWithController());
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
	public void tankDrive(double speedLeft, double speedRight) {
		robotDrive.tankDrive(speedLeft, speedRight);
		
	}
	public void driveStraight(double speed) {
		robotDrive.tankDrive(speed, speed);
	}
	
}

